live_config_reload = true

[window]
opacity = 0.85
decorations = "full"
startup_mode = "FullScreen"


[shell]
program = "/bin/zsh"

# Default colors
[colors.primary]
background = '#171d23'
foreground = '#ffffff'

# Cursor colors
[colors.cursor]
text = '#fafafa'
cursor = '#008b94'

# Normal colors
[colors.normal]
black = '#333f4a'
red = '#d95468'
green = '#8bd49c'
blue = '#539afc'
magenta = '#b62d65'
cyan = '#70e1e8'
white = '#b7c5d3'

# Bright colors
[colors.bright]
black = '#41505e'
red = '#d95468'
green = '#8bd49c'
yellow = '#ebbf83'
blue = '#5ec4ff'
magenta = '#e27e8d'
cyan = '#70e1e8'
white = '#ffffff'


[font]
size = 15
builtin_box_drawing = true

[font.normal]
family = "Fira Code"
style = "Regular"

[font.bold]
family = "Fira Code"
style = "Regular"

[font.italic]
family = "Fira Code"
style = "Regular"

[font.bold_italic]
family = "Fira Code"
style = "Regular"

[mouse]
hide_when_typing = true
bindings = [{ mouse = "Right", mods = "Control", action = "Paste" }]

[keyboard]
bindings = [{ key = "N", mods = "Control|Shift", action = "CreateNewWindow" }]

[[hints.enabled]]
command = "open"
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "U", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
