#!/usr/bin/env sh

# has() {
#     type "$1" > /dev/null 2>&1
# }

# get the active shell used by the user
active_shell=$(ps -p $$ -o comm=)

# region: Brew Activation and Completion
if has brew; then
    HOMEBREW_PREFIX="$(brew --prefix)"
    # For Zsh Shell
    if [ $active_shell = "zsh" ]; then
        FPATH="$HOMEBREW_PREFIX/share/zsh/site-functions:${FPATH}"
        autoload -Uz compinit
        compinit
    fi
    # For Bash Shell
    if [ $active_shell = "bash" ]; then
        if [[ -r "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh" ]]
        then
            source "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh"
        else
            for COMPLETION in "${HOMEBREW_PREFIX}/etc/bash_completion.d/"*
            do
            [[ -r "${COMPLETION}" ]] && source "${COMPLETION}"
            done
        fi
    fi
fi
# endregion

# region: asdf plugin load
if has asdf; then
    source "$HOMEBREW_PREFIX/opt/asdf/etc/bash_completion.d/asdf.bash"
fi
# endregion

# region: direnv setup
if has direnv; then
    eval "$(direnv hook $active_shell)"
fi
# endregion

# region: fzf plugin load
if has fzf; then
   source <(fzf --$active_shell)

    export FZF_DEFAULT_OPTS=$FZF_DEFAULT_OPTS'
    --color=fg:#d0d0d0,fg+:#d0d0d0,bg:#121212,bg+:#262626
    --color=hl:#5f87af,hl+:#5fd7ff,info:#afaf87,marker:#87ff00
    --color=prompt:#d7005f,spinner:#af5fff,pointer:#af5fff,header:#87afaf
    --color=border:#262626,label:#aeaeae,query:#d9d9d9
    --border="double" --border-label="" --preview-window="border-rounded" --prompt="> "
    --marker=">" --pointer="◆" --separator="─" --scrollbar="│"
    --info="right"'
fi
# endregion

# region: mise plugin load
if has mise; then
    eval "$(mise activate $active_shell)"
    eval "$(mise completion $active_shell)"
fi
# endregion

# region: starship prompt load
if has starship; then 
    eval "$(starship init $active_shell)"
    eval "$(starship completions $active_shell)"
fi
# endregion


# region: navi
if has navi; then
    export NAVI_CONFIG="$DOTFILES/navi/config.yml"
    eval "$(navi widget $active_shell)"
fi
# endregion