#!/usr/bin/env sh

has() {
    type "$1" > /dev/null 2>&1
}

active_shell=$(ps -p $$ -o comm=)

if has starship; then 
    eval "$(starship init $active_shell)"
    eval "$(starship completions $active_shell)"
fi