"$schema" = 'https://starship.rs/config-schema.json'

format = "$all"

[shell]
disabled = false
bash_indicator = ""
powershell_indicator = ""
cmd_indicator = ""
zsh_indicator = ""

[os]
disabled = false
format = "$symbol "


[os.symbols]
Ubuntu = ""
Windows = "🪟"
Macos = ""
AIX = "➿ "
AlmaLinux = "💠 "
Alpaquita = "🔔 "
Alpine = "🏔️ "
Amazon = "🙂 "
Android = "🤖 "
Arch = "🎗️ "
Artix = "🎗️ "
CentOS = "💠 "
Debian = "🌀 "
DragonFly = "🐉 "
Emscripten = "🔗 "
EndeavourOS = "🚀 "
Fedora = "🎩 "
FreeBSD = "😈 "
Garuda = "🦅 "
Gentoo = "🗜️ "
HardenedBSD = "🛡️ "
Illumos = "🐦 "
Kali = "🐉 "
Linux = "🐧 "
Mabox = "📦 "
Manjaro = "🥭 "
Mariner = "🌊 "
MidnightBSD = "🌘 "
Mint = "🌿 "
NetBSD = "🚩 "
NixOS = "❄️ "
OpenBSD = "🐡 "
OpenCloudOS = "☁️ "
OracleLinux = "🦴 "
Pop = "🍭 "
Raspbian = "🍓 "
RedHatEnterprise = "🎩 "
Redhat = "🎩 "
Redox = "🧪 "
RockyLinux = "💠 "
SUSE = "🦎 "
Solus = "⛵ "
Ultramarine = "🔷 "
Unknown = "❓ "
Void = "  "
openEuler = "🦉 "
openSUSE = "🦎 "

[battery]
disabled = false
full_symbol = "🔋"
charging_symbol = "⚡️"
discharging_symbol = "💀"

[character]
success_symbol = '[➜ ](bold green)'
error_symbol = '[➜ ](bold red)'

[container]
disabled = true

[directory]
read_only = "🔒"
home_symbol = "🏠"
style = "green bold"
truncation_length = 1
read_only_style = "red"

[git_branch]
symbol = '🌱 '

[python]
symbol = "🐍 "
version_format = 'v${major}.${minor}.${patch} '
format = "via [${symbol}${version}]($style) "

[ruby]
disabled = true

[terraform]
symbol = "💠 "
format = "via [${symbol}${version}]($style) "
