#!/usr/bin/env zsh

if has starship 2>/dev/null; then
    # Configure starship prompt
    set_loc "STARSHIP_CONFIG" "$DOTFILES/starship/starship.toml"

    # Activate starship in zsh
    eval "$(starship init zsh)"
fi