# hyprland.conf — entry point, sources all modules
# Edit individual module files rather than this file.

source = ~/.config/hypr/modules/monitors.conf
source = ~/.config/hypr/modules/input.conf
source = ~/.config/hypr/modules/look.conf
source = ~/.config/hypr/modules/keybinds.conf
source = ~/.config/hypr/modules/windowrules.conf
source = ~/.config/hypr/modules/autostart.conf
source = ~/.config/hypr/modules/workspaces.conf
source = ~/.config/hypr/modules/idle.conf
