# Starship for terminal prompt
brew 'starship'

# fzf for fuzzy finding in terminal
brew 'fzf'

# Text parsers for JSON and YAML
brew 'jq'
brew 'yq'

# eza for ls replacement
brew 'eza'

# direnv for environment management
brew 'direnv'

# better find
brew 'fd'

# bat
brew 'bat'
