# Starship for terminal prompt
brew 'starship'

# fzf for fuzzy finding in terminal
brew 'fzf'

# eza for ls replacement
brew 'eza'

# direnv for environment management
brew 'direnv'

# mise for managing software packages
brew 'mise'