# Firacode font
cask "font-fira-code"

# Databricks CLI
tap "databricks/tap"
brew "databricks"

# Allacritty (Terminal)
cask "alacritty"

# Azrue CLI
brew "azure-cli"

# 1Password CLI
brew '1password-cli'