preview = true
native-tls = true
link-mode = "symlink"
compile-bytecode = false

[[index]]
name = "pypi"
url = "https://pypi.org/simple"

[[index]]
name = "pypi-mirror"
url = "https://files.pythonhosted.org/simple"

[[index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"

[[index]]
name = "pytorch-cu118"
url = "https://download.pytorch.org/whl/cu118"

[[index]]
name = "pytorch-cu124"
url = "https://download.pytorch.org/whl/cu124"

[[index]]
name = "prodigy"
url = "https://1821-659B-1112-B778@download.prodi.gy/index"
explicit = true

# [[index]]
# name = "manulife-artifactory-ca"
# url = "https://artifactory.manulife.ca/artifactory/api/pypi/pypi/simple"

# [[index]]
# name = "manulife-artifactory-io
# url = "https://artifactory.platform.manulife.io/artifactory/api/pypi/pypi/simple"